"""
Django settings for confecciones_lucy project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import pymysql
pymysql.install_as_MySQLdb()
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6#04wi^8del4efi^cfgpb8n)d9rio5e!#ocurx7q=u7f1te2rr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1']
"""RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
"""

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'compras',
    'produccion',
    'ventas',
    'usuarios',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', 
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'confecciones_lucy.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuarios.context_processors.datos_usuario',
            ],
        },
    },
]


WSGI_APPLICATION = 'confecciones_lucy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# Database configuration
"""DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'Confecciones_Lucy',              
        'USER': 'sa',                            
        'PASSWORD': 'carlos2001',                
        'HOST': 'ANDRES\\ANDRES2001',            
        'PORT': '',                              
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  
        },
    }
}"""

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',   # Configuración para MySQL
        'NAME': 'sistema_casa_cambio',          # Nombre de tu base de datos
        'USER': 'root',                         # Usuario de MySQL (en tu caso 'root')
        'PASSWORD': '',                         # Si no tiene contraseña, déjalo vacío
        'HOST': 'localhost',                    # El host donde se encuentra MySQL
        'PORT': '3306',                         # Puerto de MySQL (por defecto 3306)
    }
}

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'defaultdb',
        'USER': 'avnadmin',
        'PASSWORD': 'AVNS_eksc-EPQlS3ua-OsSsH',
        'HOST': 'mysql-sistema01-sossaantelocarlosandres-6279.f.aivencloud.com',
        'PORT': 12192,
        'OPTIONS': {
            'ssl': {'ca': 'ca.pem'},
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}"""
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'usuarios.Usuario'


AUTHENTICATION_BACKENDS = ['usuarios.auth_backend.UsuarioBackend']

LOGIN_REDIRECT_URL = 'base/'  # Página a donde redirigir tras iniciar sesión
LOGIN_URL = '/login/'  # Página de login si el usuario no está autenticado
LOGOUT_REDIRECT_URL = '/login/'  # Página tras cerrar sesión

# Static files (CSS, JavaScript, Image
# https://docs.djangoproject.com/en/5.1/howto/static-files/


# Configuración de los archivos estáticos
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Si quieres servir archivos estáticos durante el desarrollo
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
